[package]
name = "tessera_text"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
tessera_color.workspace = true
parley.workspace = true
serde.workspace = true
slotmap.workspace = true
unicode-segmentation.workspace = true
hypher = { version = "0.1.7", default-features = false, features = ["alloc", "english"] }
skrifa = "0.44"

[dev-dependencies]
proptest.workspace = true
serde_json.workspace = true
