[package]
name = "tessera-renderer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Tessera Publish Renderer - Vello & WebGPU Scene Generation Pipeline"

[dependencies]
tessera-core = { workspace = true }
bevy_ecs = { workspace = true }
kurbo = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
