[package]
name = "tessera_import"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
tessera_document.workspace = true
tessera_text.workspace = true
tessera_color.workspace = true
tessera_geometry.workspace = true
zip.workspace = true
kurbo.workspace = true
roxmltree.workspace = true
thiserror.workspace = true

[dev-dependencies]
zip.workspace = true
tessera_document.workspace = true
tessera_text.workspace = true
tessera_color.workspace = true
